name: yono_business_flutter
description: YONO Business Banking - Advanced mobile application for business banking operations.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Network & API
  dio: ^5.3.4
  json_annotation: ^4.8.1

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  expansion_tile_card: ^3.0.0
  showcaseview: 2.0.3
  fl_chart: ^0.68.0
  
  # Utilities
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  intl: ^0.20.2
  uuid: ^4.0.0
  
  # Security
  local_auth: ^2.2.0
  
  # Navigation & App Features
  double_back_to_close_app: ^2.1.0
  app_settings: ^5.1.1
  keyboard_actions: ^4.2.0
  
  # Form & Input
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0
  
  # Image & Media
  image_picker: ^1.0.4
  
  # Notifications
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^16.3.2
  flutter_app_badger: ^1.5.0
  
  # Theme
  theme_provider: ^0.6.0
  flutter_dynamic_icon: ^2.1.0
  
  # Code Generation
  freezed: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  # fonts:
    # - family: InterRegular
      # fonts:
        # - asset: assets/fonts/Inter-Regular.ttf
        
    # - family: InterMedium
      # fonts:
        # - asset: assets/fonts/Inter-Medium.ttf
        
    # - family: InterSemiBold
      # fonts:
        # - asset: assets/fonts/Inter-SemiBold.ttf
        
    # - family: InterBold
      # fonts:
        # - asset: assets/fonts/Inter-Bold.ttf